const API='https://browser-app-lab.vercel.app/api';
const MAX_DONGS=200,BATCH=6,GAP=250,BLOCK_PAUSE=5000,DONG_TTL=86400000,AUTO_RETRY_DELAY=3000;
const LS={regions:'dgn_regions_v2',selected:'dgn_selected_v2',dongs:'dgn_dongs_v2',exclude:'dgn_exclude_v2',diag:'dgn_diag_v22'};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let mode='sell',sortMode='new',onSale=false,myPos=null,searching=false;
let regions=load(LS.regions,[]),selected=new Set(load(LS.selected,[])),dongCache=load(LS.dongs,{}),excludes=load(LS.exclude,{sell:[],group:[],comm:[]});
let items=[],codeMeta={},failedCodes=[],lastMeta={};
const state={sell:{q:'',items:[],meta:{}},group:{q:'',items:[],meta:{}},comm:{q:'',items:[],meta:{}}};
const endpoint=()=>mode==='group'?'daangn-group':mode==='comm'?'daangn-community':'daangn';
function placeholder(){return mode==='sell'?'검색어를 입력하세요':mode==='group'?'모임 검색 (예: 등산, 독서)':'동네생활 검색 (예: 맛집, 분실)'}
function setStatus(s){$('status').innerHTML=s||''}
function toggleClear(){$('clear').classList.toggle('show',!!$('q').value)}
function setMode(m){if(m===mode)return;state[mode]={q:$('q').value,items:[...items],meta:lastMeta};mode=m;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('on',b.dataset.mode===m));const sell=m==='sell';$('priceChip').style.display=sell?'':'none';$('distChip').style.display=sell?'':'none';$('saleChip').style.display=sell?'':'none';$('newChip').style.display=m==='group'?'none':'';$('q').placeholder=placeholder();$('q').value=state[m].q||'';items=[...(state[m].items||[])];lastMeta=state[m].meta||{};failedCodes=[];$('retry').classList.remove('show');toggleClear();render();updateStatus();renderTags()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('q').oninput=toggleClear;$('clear').onclick=()=>{$('q').value='';toggleClear();$('q').focus()};$('q').onkeydown=e=>{if(e.key==='Enter'){e.target.blur();searchAll()}};$('go').onclick=()=>searchAll();
function openSheet(id,b){$(id).classList.add('open');$(b).classList.add('open')}function closeSheet(id,b){$(id).classList.remove('open');$(b).classList.remove('open')}
$('regionChip').onclick=()=>{renderRegions();openSheet('regionSheet','regionBack')};$('regionBack').onclick=()=>closeSheet('regionSheet','regionBack');$('regionDone').onclick=()=>{closeSheet('regionSheet','regionBack');if($('q').value.trim()&&selected.size)searchAll()};$('regionClear').onclick=()=>{selected.clear();save(LS.selected,[...selected]);renderRegions();updateRegionChip()};
async function loadRegions(){try{const r=await fetch(`${API}/daangn-regions`),d=await r.json();if(!r.ok||!Array.isArray(d.list))throw new Error(d.error||'지역 목록 오류');regions=d.list;save(LS.regions,regions);updateRegionChip()}catch(e){if(!regions.length)setStatus(`<span class="err">지역 목록 로딩 실패: ${esc(e.message||e)}</span>`)}}
async function dongsFor(r,force=false){if(!r)return[];const hit=dongCache[r.code];if(!force&&hit&&Date.now()-hit.at<DONG_TTL&&Array.isArray(hit.list))return hit.list;let last;for(let a=0;a<2;a++){try{const res=await fetch(`${API}/daangn-dongs?gu=${encodeURIComponent(r.name)}&province=${encodeURIComponent(r.province)}`),d=await res.json();if(!res.ok||!Array.isArray(d.list)||!d.list.length)throw new Error(d.error||'동 목록 없음');dongCache[r.code]={at:Date.now(),list:d.list};save(LS.dongs,dongCache);return d.list}catch(e){last=e;if(!a)await sleep(700)}}throw last}
async function projectedCount(add,r){let n=0;for(const c of selected)n+=(await dongsFor(regions.find(x=>x.code===c))).length;if(add&&!selected.has(add))n+=(await dongsFor(r)).length;return n}
function renderRegions(){if(!regions.length){$('regionBody').innerHTML='<div class="empty">지역 목록 불러오는 중...</div>';return}const by={};regions.forEach(r=>(by[r.province]??=[]).push(r));let h='';for(const p of ['서울특별시','경기도']){const list=by[p]||[];h+=`<div class="prov"><strong>${p}</strong><button data-prov="${p}">${list.every(r=>selected.has(r.code))?'전체 해제':'전체 선택'}</button></div><div class="guWrap">${list.map(r=>`<button class="gu ${selected.has(r.code)?'on':''}" data-code="${esc(r.code)}">${esc(r.name)}</button>`).join('')}</div>`}$('regionBody').innerHTML=h;document.querySelectorAll('.gu').forEach(b=>b.onclick=async()=>{const c=b.dataset.code,r=regions.find(x=>x.code===c);if(selected.has(c))selected.delete(c);else{try{if(await projectedCount(c,r)>MAX_DONGS){$('limit').innerHTML=`<span class="err">동네 ${MAX_DONGS}곳을 넘을 수 없습니다.</span>`;return}}catch(e){$('limit').innerHTML=`<span class="err">${esc(r.name)} 동 목록 확인 실패</span>`;return}selected.add(c)}save(LS.selected,[...selected]);renderRegions();updateRegionChip()});document.querySelectorAll('[data-prov]').forEach(b=>b.onclick=async()=>{const list=by[b.dataset.prov]||[],all=list.every(r=>selected.has(r.code));if(all)list.forEach(r=>selected.delete(r.code));else for(const r of list){if(selected.has(r.code))continue;try{if(await projectedCount(r.code,r)>MAX_DONGS)break;selected.add(r.code)}catch{break}}save(LS.selected,[...selected]);renderRegions();updateRegionChip()});updateRegionChip()}
function updateRegionChip(){const rs=regions.filter(r=>selected.has(r.code));$('regionChip').textContent=!rs.length?'지역 선택 ▾':rs.length===1?`${rs[0].name} ▾`:`${rs[0].name} 외 ${rs.length-1} ▾`;$('regionChip').classList.toggle('on',!!rs.length);$('regionCount').textContent=rs.length?`${rs.length}곳 선택`:'';$('limit').textContent=`동네 최대 ${MAX_DONGS}곳 · 차단 감지 시에만 자동 안정화`}
async function selectedCodes(){const out=[],fails=[];codeMeta={};for(const r of regions.filter(x=>selected.has(x.code))){try{for(const d of await dongsFor(r)){out.push(d.code);codeMeta[d.code]={gu:d.gu||r.name,dong:d.dong||null}}}catch{fails.push(r.name)}}return{codes:[...new Set(out)].slice(0,MAX_DONGS),dongFails:fails}}
$('excChip').onclick=()=>{renderTags();openSheet('excSheet','excBack')};$('excBack').onclick=()=>closeSheet('excSheet','excBack');$('excDone').onclick=()=>{closeSheet('excSheet','excBack');render();updateStatus()};$('excAdd').onclick=addExc;$('excInput').onkeydown=e=>{if(e.key==='Enter')addExc()};$('excClear').onclick=()=>{excludes[mode]=[];save(LS.exclude,excludes);renderTags();render();updateStatus()};function addExc(){const v=$('excInput').value.trim();if(v&&!excludes[mode].includes(v))excludes[mode].push(v);$('excInput').value='';save(LS.exclude,excludes);renderTags();render();updateStatus()}function renderTags(){const a=excludes[mode]||[];$('excCount').textContent=a.length?`${a.length}개`:'';$('tags').innerHTML=a.map((x,i)=>`<button class="tag" data-i="${i}">${esc(x)} ×</button>`).join('');document.querySelectorAll('.tag').forEach(b=>b.onclick=()=>{a.splice(+b.dataset.i,1);save(LS.exclude,excludes);renderTags();render();updateStatus()});$('excChip').classList.toggle('on',a.length>0)}
$('newChip').onclick=()=>setSort('new');$('priceChip').onclick=()=>setSort('price');$('distChip').onclick=()=>setSort('dist');$('saleChip').onclick=()=>{onSale=!onSale;$('saleChip').classList.toggle('on',onSale);render();updateStatus()};function setSort(m){sortMode=m;['new','price','dist'].forEach(x=>$(`${x}Chip`).classList.toggle('on',x===m));if(m==='dist'&&!myPos)navigator.geolocation.getCurrentPosition(p=>{myPos=[p.coords.latitude,p.coords.longitude];render()},()=>{sortMode='new';$('newChip').classList.add('on');$('distChip').classList.remove('on');setStatus('<span class="err">위치 권한이 없어 가까운순을 사용할 수 없습니다.</span>')});render()}
const coords={강남구:[37.517,127.047],서초구:[37.484,127.033],송파구:[37.515,127.106],강동구:[37.53,127.124],마포구:[37.566,126.902],종로구:[37.573,126.979],성동구:[37.563,127.036],광진구:[37.538,127.082],용산구:[37.532,126.99],영등포구:[37.526,126.896],수원시:[37.263,127.029],성남시:[37.42,127.127],고양시:[37.658,126.832],용인시:[37.241,127.178]};function distance(it){if(!myPos)return 1e9;const c=coords[it.gu]||coords[(it.gu||'').split(' ')[0]];if(!c)return 1e9;return Math.hypot((myPos[0]-c[0])*111,(myPos[1]-c[1])*88)}
function visible(){let a=items.filter(it=>!(excludes[mode]||[]).some(w=>(it.title||'').toLowerCase().includes(w.toLowerCase())));if(mode==='sell'&&onSale)a=a.filter(it=>it.status==='on_sale');if(sortMode==='price'&&mode==='sell')a.sort((x,y)=>(x.price??1e15)-(y.price??1e15));else if(sortMode==='dist'&&mode==='sell')a.sort((x,y)=>distance(x)-distance(y));else if(sortMode==='new')a.sort((x,y)=>(y.sortTime||0)-(x.sortTime||0));return a}
const fmtPrice=v=>v==null?'가격 정보 없음':v===0?'나눔':Number(v).toLocaleString('ko-KR')+'원';function ago(t){if(!t)return'';const s=Math.max(0,(Date.now()-t)/1000);if(s<60)return'방금 전';if(s<3600)return`${Math.floor(s/60)}분 전`;if(s<86400)return`${Math.floor(s/3600)}시간 전`;return`${Math.floor(s/86400)}일 전`}
function render(){const a=visible();if(!a.length){$('results').innerHTML=searching?'':items.length?'<div class="empty">필터 조건에 맞는 결과가 없습니다.</div>':'<div class="empty">검색 결과가 없습니다.</div>';return}$('results').innerHTML=a.map(it=>{const img=it.thumb?`<img class="thumb" src="${esc(it.thumb)}" loading="lazy">`:'<div class="thumb"></div>';if(mode==='sell')return`<a class="card ${it.status==='sold'?'sold':''}" href="${esc(it.url)}" target="_blank">${img}<div class="info"><div class="title">${esc(it.title)}</div><div class="price">${fmtPrice(it.price)}</div><div class="meta">${esc(it.dong||it.gu||'')}${it.sortTime?' · '+ago(it.sortTime):''}${it.isBoosted?' · 끌올':''}${it.status==='sold'?' · 판매완료':''}</div></div></a>`;if(mode==='group')return`<a class="card" href="${esc(it.url)}" target="_blank">${img}<div class="info"><div class="title">${esc(it.title)}</div><div class="meta">${esc(it.place||it.gu||'')}${it.members!=null?' · 멤버 '+Number(it.members).toLocaleString()+'명':''}</div>${it.desc?`<div class="desc">${esc(it.desc)}</div>`:''}</div></a>`;return`<a class="card" href="${esc(it.url)}" target="_blank">${img}<div class="info"><div class="title">${esc(it.title)}</div><div class="meta">${esc(it.dong||it.gu||'')}${it.sortTime?' · '+ago(it.sortTime):''}</div>${it.desc?`<div class="desc">${esc(it.desc)}</div>`:''}</div></a>`}).join('')}
function updateStatus(){if(!lastMeta.codes)return setStatus('');let s=`동네 <b>${lastMeta.codes}</b>곳 · 정상 <b>${lastMeta.ok}</b>곳 · 결과 <b>${visible().length}</b>건 · ${lastMeta.sec}초`;if(lastMeta.recovered)s+=` · 재시도 복구 <b>${lastMeta.recovered}</b>곳`;if(lastMeta.pauses)s+=` · 안정화 ${lastMeta.pauses}회`;if(lastMeta.failed)s+=` · <span class="err">실패 ${lastMeta.failed}곳</span>`;if(lastMeta.blocked)s+=` · <span class="err">차단응답 ${lastMeta.blocked}곳</span>`;if(lastMeta.dongFails)s+=` · <span class="err">동 목록 실패 ${lastMeta.dongFails}곳</span>`;setStatus(s);$('retry').classList.toggle('show',failedCodes.length>0)}
async function requestBatch(q,codes){const r=await fetch(`${API}/${endpoint()}?q=${encodeURIComponent(q)}&regions=${encodeURIComponent(codes.join(','))}`),d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function pass(q,codes,label='검색'){const seen=new Set(items.map(x=>x.url));let ok=0,blocked=0,pauses=0,fail=[];for(let i=0;i<codes.length;i+=BATCH){const b=codes.slice(i,i+BATCH),done=Math.min(i+BATCH,codes.length);setStatus(`<span class="spin"></span>${label} ${done}/${codes.length} · 현재 <b>${items.length}</b>건`);let blockedThisBatch=0;try{const d=await requestBatch(q,b);ok+=d.okRegionCount??Math.max(0,b.length-(d.errors||[]).length);blockedThisBatch=d.blockedCount||0;blocked+=blockedThisBatch;for(const e of d.errors||[])fail.push(e.region);for(const it of d.items||[]){if(seen.has(it.url))continue;seen.add(it.url);const m=codeMeta[it.region]||{};items.push({...it,gu:m.gu||it.gu||'',dong:it.dong||m.dong||null})}}catch{fail.push(...b)}render();if(done<codes.length){if(blockedThisBatch>0){pauses++;setStatus(`<span class="spin"></span>차단 응답 감지 · ${BLOCK_PAUSE/1000}초 안정화 후 계속`);await sleep(BLOCK_PAUSE)}else await sleep(GAP)}}return{ok,blocked,pauses,failed:[...new Set(fail)]}}
async function searchAll(opts={}){const q=$('q').value.trim();if(!q){setStatus('<span class="err">검색어를 입력하세요.</span>');return}if(!selected.size){setStatus('<span class="err">지역을 먼저 선택하세요.</span>');renderRegions();openSheet('regionSheet','regionBack');return}if(searching)return;searching=true;$('go').disabled=true;const t0=Date.now();try{let codes,dongFails=[],manualRetry=!!opts.retryOnly;if(manualRetry){codes=[...failedCodes];failedCodes=[]}else{items=[];failedCodes=[];$('results').innerHTML='<div class="loading"><span class="spin"></span> 동네 목록 확인 중...</div>';const out=await selectedCodes();codes=out.codes;dongFails=out.dongFails}if(!codes.length)throw new Error('검색할 동네 코드가 없습니다.');const first=await pass(q,codes,manualRetry?'재검색':'검색');let finalFailed=first.failed,totalBlocked=first.blocked,totalPauses=first.pauses,recovered=0;if(!manualRetry&&finalFailed.length){setStatus(`<span class="spin"></span>실패 ${finalFailed.length}곳 빠른 자동 재시도 준비 중...`);await sleep(AUTO_RETRY_DELAY);const before=finalFailed.length,retry=await pass(q,finalFailed,'자동 재시도');finalFailed=retry.failed;recovered=Math.max(0,before-finalFailed.length);totalBlocked+=retry.blocked;totalPauses+=retry.pauses}failedCodes=finalFailed;lastMeta={codes:codes.length,ok:Math.max(0,codes.length-failedCodes.length),failed:failedCodes.length,blocked:totalBlocked,pauses:totalPauses,dongFails:dongFails.length,recovered,sec:((Date.now()-t0)/1000).toFixed(1),batch:BATCH,gap:GAP,blockPause:BLOCK_PAUSE};save(LS.diag,{at:Date.now(),mode,q,...lastMeta,failedCodes});state[mode]={q,items:[...items],meta:lastMeta};render();updateStatus()}catch(e){setStatus(`<span class="err">검색 실패: ${esc(e.message||e)}</span>`)}finally{searching=false;$('go').disabled=false;if(!items.length)render()}}
$('retry').onclick=()=>{if(failedCodes.length)searchAll({retryOnly:true})};
(function(){let y=null,pulling=false;document.addEventListener('touchstart',e=>{if(searching||e.target.closest('.sheet'))return;if(scrollY<=0){y=e.touches[0].clientY;pulling=true}},{passive:true});document.addEventListener('touchend',e=>{if(!pulling)return;const d=(e.changedTouches[0]?.clientY||0)-(y||0);pulling=false;y=null;if(d>145&&$('q').value.trim()&&selected.size)searchAll()})})();
$('q').placeholder=placeholder();toggleClear();updateRegionChip();renderTags();loadRegions();